# app/config/settings.yaml

# Environment
DOMAIN_BASE: &DOMAIN_BASE gangsterclub.nl
SSL: true
SRC_CONTROLLER: 'src\\Controller\\'
# DEVELOPER_IPS can access game when appOffline below is true.
DEVELOPER_IPS:
    - 127.0.0.1
    - 'fe80::'

# Application
APP_NAME: GangsterClub Online
APP_DOMAIN: gcov1.*DOMAIN_BASE
APP_DEVELOPMENT: true
APP_MAX_AGE: 7200
APP_OFFLINE: false

# Database
DB_CONN: &DB_CONN mysql
DB_HOST: &DB_HOST localhost
DB_NAME: &DB_NAME gco
DB_CONN_STRING: '*DB_CONN:host=*DB_HOST;dbname=*DB_NAME'
DB_USER: root
DB_PASS:

# Email
MAIL_HOST: mail.gangsterclub.nl
MAIL_ADDR: no-reply@gangsterclub.nl
MAIL_PASS: n0r3p1yp4S5w0rd
# MAIL_PORT defaults to 587 when set to false.
MAIL_PORT: false
