# app/config/routes.yaml
home:
    path: /
    controller: Home
    methods: ['GET', 'HEAD']

hello:
    path: /hello(?:/)?(?:/{name})?
    controller: Index::sayHello
    methods: ['GET', 'HEAD']

staticExample:
    path: /static/example
    controller: StaticExample
    methods: ['GET', 'HEAD']

setLocale:
    path: /set/locale/{locale}
    controller: SetLocale
    methods: ['GET', 'HEAD']
